#!C:\Users\henry\OneDrive - The Hong Kong Polytechnic University\Y4_SEM1\FYP\venv_lora_win\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
